### ISSUE TITLE
PersistentKeepalive arguments

### ISSUE THREAD

**Issue by adesanto-vds** [k4yt3x/wg-meshconf#17]
The  PersistentKeepalive field is in the showpeers table but it is not possible to modify it using addpeer or updatepeer.

Is it in the roadmap to add this option?

**Comment by k4yt3x** [comment]
Sounds like a valid point. I'll take a look.

**Comment by mosespi** [comment]
#20 
And thanks for the great tool!

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/119200457-f8dd2e80-ba5a-11eb-99a3-2fcd13162ac9.png)

**Comment by k4yt3x** [comment]
Sorry for the long wait -- I've been a bit tied up.
I think it works.
