### ISSUE TITLE
What is the status/future of wg-meshconf ?  Is it considered ready for use?

### ISSUE THREAD

**Issue by bmullan** [k4yt3x/wg-meshconf#21]
What is the status/future of wg-meshconf re  Is it considered "ready-for-use" ?

Thanks
Brian

**Comment by dimon222** [comment]
Well, it's already in pretty good shape, so probably for majority of scenarios you could use it with no efforts in semi-production ready sense. However, it doesn't cover all available options of Wireguard like discussed in issues #10 #14 #17

**Comment by k4yt3x** [comment]
This tool isn't a background service or anything, it's a configuration generation tool. Therefore, it either works or doesn't work. I don't think there's a middle ground where it "works but works poorly or insecurely."

I was already using it for my production environment when I initially built it 3 years ago. I think you can safely use it for whatever you need it for.
