### ISSUE TITLE
Output is created in `site-packages` under `venv`

### ISSUE THREAD

**Issue by plattrap** [k4yt3x/wg-meshconf#23]
I installed `wg-meshconf` using a `venv` for testing on my machine.

When I created the output files, they appeared under the `site-packages/wg_meshconf` folder.

```
$ python3 -m venv wg-meshconf
$ . wg-meshconf/bin/activate
$ wg-meshconf addpeer ...

$ wg-meshconf genconfig
Creating output directory: /home/user/wg-meshconf/lib/python3.8/site-packages/wg_meshconf/output
```

**Comment by dimon222** [comment]
Technically speaking it seems intentional.
https://github.com/k4yt3x/wg-meshconf/blob/6673a6d2f699ea42aeae52fdac5133ddb9c94d32/wg_meshconf/wg_meshconf.py#L132

@k4yt3x should we consider using path relative to current directory instead?

**Comment by k4yt3x** [comment]
Yes I think we should change how that works since we're allowing this package to be installed with pip now.
I'll update it.

**Comment by k4yt3x** [comment]
Just fixed in the newest update.
I'll push it to pip later.
